### ISSUE TITLE
Organize the numbering of Extensions

### ISSUE THREAD

**Issue by genesisgabiola** [KarenEfereyan/extensions-4-every-developer#14]
Hard to distinguish if some content is still part of the previous or next extension. Having them numbered correctly can help users see the list and contents of extensions easily.

**Comment by KarenEfereyan** [comment]
@genesisgabiola thats true. Hold on one minute lets see what can be done

**Comment by KarenEfereyan** [comment]
@genesisgabiola what do you propose could be done? Can you do the reordering and make a PR?

**Comment by KarenEfereyan** [comment]
@genesisgabiola  I have the PR referencing this. So I will close the PR
