### ISSUE TITLE
Common Format for filling README

### ISSUE THREAD

**Issue by capturemathan** [KarenEfereyan/extensions-4-every-developer#21]
Since many developers add their findings to `README`, the features and availability are in `bold` tags rather than the heading of the extension making it difficult to read. Instead, a small note can be added to `README` with the format :wink:

**Comment by KarenEfereyan** [comment]
@capturemathan can you explain better? I have actually been thinking of a way i can make the readme even better

**Comment by josylad** [comment]
> @capturemathan can you explain better? I have actually been thinking of a way i can make the readme even better

I think what he is saying is that the name of each extension should be a heading, like H3 and be bold. 
right now, the extensions are just regular paragraphs and it's hard to read.

**Comment by KarenEfereyan** [comment]
Oh okay. Noted. Its independence and theres no light well i mean electricity so im just kinda stuck. When i do get light ill work on that

**Comment by capturemathan** [comment]
> @capturemathan can you explain better? I have actually been thinking of a way i can make the readme even better

Actually what I meant was, have a `snippet.md` that the contributors just need to edit and paste in `README.MD` like this
`
# Your title here
## Availability here
`
I would be happy to work on this 🎉

**Comment by KarenEfereyan** [comment]
Oh @capturemathan definitely ! That makes a lot of sense. They just have to fill in the necessary details. Maybe you can create the file? But the question i have is, howw will it now get added to the readme once theyve filled it in? Wouldnt that require a github action? But ill assign the issue to you right now.

**Comment by capturemathan** [comment]
> Oh @capturemathan definitely ! That makes a lot of sense. They just have to fill in the necessary details. Maybe you can create the file? But the question i have is, howw will it now get added to the readme once theyve filled it in? Wouldnt that require a github action? But ill assign the issue to you right now.

No @KarenEfereyan , the newbies need to visit `snippet.md`, copy the raw code from there and paste in `readme.md` (or) we can directly paste the format code in `README.MD`. Whats your say ?

**Comment by KarenEfereyan** [comment]
Hmm. I'm not sure. I'm on my phone right now as my laptop is dead. But I prefer the idea of making a separate snippet.MD file. @josylad what are your thoughts on this?

**Comment by josylad** [comment]
> Hmm. I'm not sure. I'm on my phone right now as my laptop is dead. But I prefer the idea of making a separate snippet.MD file. @josylad what are your thoughts on this?

it's a good idea. 
I was thing in the same way too. 
A formatting guidelines that contributors copy, paste and edit when adding their own extensions. 

@capturemathan I have updated the README now, all extensions name has H3, and features have H4. So, it is more readable.

**Comment by capturemathan** [comment]
> > Hmm. I'm not sure. I'm on my phone right now as my laptop is dead. But I prefer the idea of making a separate snippet.MD file. @josylad what are your thoughts on this?
> 
> it's a good idea.
> I was thing in the same way too.
> A formatting guidelines that contributors copy, paste and edit when adding their own extensions.
> 
> @capturemathan I have updated the README now, all extensions name has H3, and features have H4. So, it is more readable.

Yeah its looking good. I will just add a snippet.md with the same format and make a PR. Is it okay ?

**Comment by KarenEfereyan** [comment]
Sure @capturemathan go on
